name: Sync To Gitee
on:
  push:
    # push 到main分支时触发
    branches: [main]
  schedule:
    # 每天触发一次
    - cron: '0 3 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:Vekixx/cnm3u.git"
          destination-repo: "git@gitee.com:Vekixx/cnm3u.git"
